sudo: required
language: generic

services:
  - docker

before_install:
 - docker build -t rualoguh/COMPLEXFIBBOSITE-GUIDED-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true rualoguh/COMPLEXFIBBOSITE-GUIDED-test npm test

after_success:
  - docker build -rualoguh/multi-client ./client
  - docker build -rualoguh/multi-client ./nginx
  - docker build -rualoguh/multi-client ./server
  - docker build -rualoguh/multi-client ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  - docker push rualoguh/multi-client
  - docker push rualoguh/multi-niginx
  - docker push rualoguh/multi-server
  - docker push rualoguh/multi-worker



  #new code to be added 